name: SparkAbilities
version: 1.0
main: com.omprepakash39.spark.SparkAbilityPlugin
api-version: '1.21'
commands:
  sparkgui:
    description: Opens the Spark Abilities GUI
    permission: spark.admin
    permission-message: You do not have permission to use this command.
