name: SparkAbilities
version: 1.0
main: com.sparkmc.abilities.SparkAbilities
api-version: 1.20
commands:
  sparkgui:
    description: Opens the Spark Ability GUI
    permission: spark.admin
    usage: /sparkgui
